name: kaixin
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - EMAIL_USER=yourusername
      - EMAIL_APP_PASSWORD=yourpassword
      - MONGO_URI=mongodb://mongo:27017/restaurant
    depends_on:
      - mongo

  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
